version: "3.8"

services:
  db:
    image: postgres
    env_file:
      - studentcourse/.env
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=californiA.wave9
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
